apiVersion: v1
kind: Service
metadata:
  name: {{ include "azdo-runner-operator.fullname" . }}
  labels:
    {{- include "azdo-runner-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "azdo-runner-operator.selectorLabels" . | nindent 4 }}
