apiVersion: kara.felukka.org/v1
kind: RunnerPool
metadata:
  labels:
    app.kubernetes.io/name: azdo-operator
    app.kubernetes.io/managed-by: kustomize
  name: runnerpool-sample
spec:
  azUrl: "https://dev.azure.com/your-org"
  pool: "Default"
  patSecretName: "azdo-pat"
  image: "mcr.microsoft.com/azure-pipelines/vsts-agent"
  maxAgents: 5
  minAgents: 0
