namespace: azdorunner-system
namePrefix: azdorunner-
labels:
- includeSelectors: true
  pairs:
    operator: azdorunner
resources:
- operator-role.yaml
- operator-role-binding.yaml
- deployment.yaml
- runnerpools_devops_atos_net.yaml
- namespace.yaml
images:
- name: operator
  newName: accessible-docker-image
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization