name: Build and Push Agent Docker Images

on:
  push:
    tags:
      - "*"
    branches:
      - main
    paths:
      - "agent/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/agent

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Only run if this is not from a pull request
    if: github.event_name != 'pull_request'

    strategy:
      matrix:
        runtime:
          - type: base
            suffix: ""
          - type: java
            suffix: "-java"
          - type: dotnet
            suffix: "-dotnet"
          - type: nodejs
            suffix: "-nodejs"

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest${{ matrix.runtime.suffix }}
            type=raw,value={{sha}}${{ matrix.runtime.suffix }},format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./agent
          file: ./agent/Dockerfile
          push: true
          build-args: |
            RUNTIME_TYPE=${{ matrix.runtime.type }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
