---
name: Release Helm Chart
on:
  push:
    tags: ["*"]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0
      - name: Package Helm chart
        run: |
          helm package chart/azdo-runner-operator --destination packaged
      - name: Create Helm repo index
        run: |
          helm repo index packaged --url https://${{ github.repository_owner }}.github.io/charts

      - name: Checkout GitHub Pages repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
          token: ${{ secrets.GH_PAGES_TOKEN }}
          path: gh-pages

      - name: Copy packaged charts to gh-pages repo
        run: |
          mkdir -p gh-pages/charts
          cp -r packaged/* gh-pages/charts/

      - name: Commit and push charts to GitHub Pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add charts
          git commit -m "Update Helm charts" || echo "No changes to commit"
          git push
