---
name: Release Helm Chart
on:
  push:
    tags: ['*']
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0
      - name: Package Helm chart
        run: |
          helm package chart/azdo-runner-operator --destination packaged
      - name: Create Helm repo index
        run: |
          helm repo index packaged --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged
          publish_branch: gh-pages
          force_orphan: true
